// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/go-gorm/gendemo/biz/model"
)

func newAddr(db *gorm.DB) addr {
	_addr := addr{}

	_addr.addrDo.UseDB(db)
	_addr.addrDo.UseModel(&model.Addr{})

	tableName := _addr.addrDo.TableName()
	_addr.ALL = field.NewField(tableName, "*")
	_addr.ID = field.NewInt64(tableName, "id")
	_addr.Street = field.NewString(tableName, "street")
	_addr.UserID = field.NewInt64(tableName, "user_id")

	_addr.fillFieldMap()

	return _addr
}

type addr struct {
	addrDo addrDo

	ALL    field.Field
	ID     field.Int64
	Street field.String
	UserID field.Int64

	fieldMap map[string]field.Expr
}

func (a addr) Table(newTableName string) *addr {
	a.addrDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a addr) As(alias string) *addr {
	a.addrDo.DO = *(a.addrDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *addr) updateTableName(table string) *addr {
	a.ALL = field.NewField(table, "*")
	a.ID = field.NewInt64(table, "id")
	a.Street = field.NewString(table, "street")
	a.UserID = field.NewInt64(table, "user_id")

	a.fillFieldMap()

	return a
}

func (a *addr) WithContext(ctx context.Context) *addrDo { return a.addrDo.WithContext(ctx) }

func (a addr) TableName() string { return a.addrDo.TableName() }

func (a addr) Alias() string { return a.addrDo.Alias() }

func (a *addr) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *addr) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["id"] = a.ID
	a.fieldMap["street"] = a.Street
	a.fieldMap["user_id"] = a.UserID
}

func (a addr) clone(db *gorm.DB) addr {
	a.addrDo.ReplaceDB(db)
	return a
}

type addrDo struct{ gen.DO }

func (a addrDo) Debug() *addrDo {
	return a.withDO(a.DO.Debug())
}

func (a addrDo) WithContext(ctx context.Context) *addrDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a addrDo) ReadDB() *addrDo {
	return a.Clauses(dbresolver.Read)
}

func (a addrDo) WriteDB() *addrDo {
	return a.Clauses(dbresolver.Write)
}

func (a addrDo) Clauses(conds ...clause.Expression) *addrDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a addrDo) Returning(value interface{}, columns ...string) *addrDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a addrDo) Not(conds ...gen.Condition) *addrDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a addrDo) Or(conds ...gen.Condition) *addrDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a addrDo) Select(conds ...field.Expr) *addrDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a addrDo) Where(conds ...gen.Condition) *addrDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a addrDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *addrDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a addrDo) Order(conds ...field.Expr) *addrDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a addrDo) Distinct(cols ...field.Expr) *addrDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a addrDo) Omit(cols ...field.Expr) *addrDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a addrDo) Join(table schema.Tabler, on ...field.Expr) *addrDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a addrDo) LeftJoin(table schema.Tabler, on ...field.Expr) *addrDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a addrDo) RightJoin(table schema.Tabler, on ...field.Expr) *addrDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a addrDo) Group(cols ...field.Expr) *addrDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a addrDo) Having(conds ...gen.Condition) *addrDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a addrDo) Limit(limit int) *addrDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a addrDo) Offset(offset int) *addrDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a addrDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *addrDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a addrDo) Unscoped() *addrDo {
	return a.withDO(a.DO.Unscoped())
}

func (a addrDo) Create(values ...*model.Addr) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a addrDo) CreateInBatches(values []*model.Addr, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a addrDo) Save(values ...*model.Addr) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a addrDo) First() (*model.Addr, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Addr), nil
	}
}

func (a addrDo) Take() (*model.Addr, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Addr), nil
	}
}

func (a addrDo) Last() (*model.Addr, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Addr), nil
	}
}

func (a addrDo) Find() ([]*model.Addr, error) {
	result, err := a.DO.Find()
	return result.([]*model.Addr), err
}

func (a addrDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Addr, err error) {
	buf := make([]*model.Addr, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a addrDo) FindInBatches(result *[]*model.Addr, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a addrDo) Attrs(attrs ...field.AssignExpr) *addrDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a addrDo) Assign(attrs ...field.AssignExpr) *addrDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a addrDo) Joins(fields ...field.RelationField) *addrDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a addrDo) Preload(fields ...field.RelationField) *addrDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a addrDo) FirstOrInit() (*model.Addr, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Addr), nil
	}
}

func (a addrDo) FirstOrCreate() (*model.Addr, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Addr), nil
	}
}

func (a addrDo) FindByPage(offset int, limit int) (result []*model.Addr, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a addrDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a addrDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a *addrDo) withDO(do gen.Dao) *addrDo {
	a.DO = *do.(*gen.DO)
	return a
}
