// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJustUser = "user"

// JustUser mapped from table <user>
type JustUser struct {
	ID             int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           *string    `gorm:"column:name" json:"name"`
	Address        *string    `gorm:"column:address" json:"address"`
	RegisterTime   *time.Time `gorm:"column:register_time" json:"register_time"`
	Alive          *bool      `gorm:"column:alive" json:"alive"`
	CreatedAt      *time.Time `gorm:"column:created_at" json:"created_at"`
	CompanyID      *int64     `gorm:"column:company_id;default:666" json:"company_id"`
	PrivateURL     *string    `gorm:"column:private_url;default:https://a.b.c" json:"private_url"`
	XMLHTTPRequest *string    `gorm:"column:xmlHTTPRequest;default:' '" json:"xmlHTTPRequest"`
	JStr           *string    `gorm:"column:jStr" json:"jStr"`
	Geo            *string    `gorm:"column:geo" json:"geo"`
	Mint           *int32     `gorm:"column:mint" json:"mint"`
	Blank          *string    `gorm:"column:blank;default:' '" json:"blank"`
}

// TableName JustUser's table name
func (*JustUser) TableName() string {
	return TableNameJustUser
}
