// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm/schema"
)

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Extra string `gorm:"column:extra;not null;serializer:json" json:"extra"`
}

func (*Role) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameRole
	}
	return namer.TableName(TableNameRole)
}
