// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Extra     string         `gorm:"column:extra" json:"extra"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`           // 删除时间
	IsDeleted int32          `gorm:"column:is_deleted;not null;comment:是否已删除" json:"is_deleted"` // 是否已删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
